[package]
name = "lockin-stake"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lockin_stake"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token"] }
solana-program = "1.18.26"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


