name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'lockin-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lockin-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run prisma:migrate:deploy

      # Build and deploy steps go here (to your infra). Placeholder:
      - name: Build
        run: npm run build

      - name: Done
        run: echo "Migrations applied, build ready. Add your deploy step here."


